import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import { env } from './config/env.js';
import { errorHandler, notFound } from './common/errors.js';
import { authRouter } from './modules/auth/auth.routes.js';
import { jobsRouter } from './modules/jobs/jobs.routes.js';
import { applicationsRouter } from './modules/applications/applications.routes.js';
import { profilesRouter } from './modules/profiles/profiles.routes.js';
import { companiesRouter } from './modules/companies/companies.routes.js';
import { notificationsRouter } from './modules/notifications/notifications.routes.js';
import { messagesRouter } from './modules/messages/messages.routes.js';
import { adminRouter } from './modules/admin/admin.routes.js';
import { billingRouter } from './modules/billing/billing.routes.js';
import { alertsRouter } from './modules/alerts/alerts.routes.js';
import { resumesRouter } from './modules/profiles/resumes.routes.js';

export const app = express();
app.use(helmet());
app.use(cors({ origin: env.WEB_ORIGIN, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use('/api/v1/auth', rateLimit({ windowMs: 15 * 60 * 1000, limit: 50 }), authRouter);
app.use('/api/v1/jobs', jobsRouter);
app.use('/api/v1', applicationsRouter);
app.use('/api/v1', profilesRouter);
app.use('/api/v1', resumesRouter);
app.use('/api/v1/companies', companiesRouter);
app.use('/api/v1/notifications', notificationsRouter);
app.use('/api/v1/conversations', messagesRouter);
app.use('/api/v1/admin', adminRouter);
app.use('/api/v1', billingRouter);
app.use('/api/v1/job-alerts', alertsRouter);
app.get('/health', (_req, res) => res.status(200).json({ status: 'ok' }));

const swaggerSpec = swaggerJsdoc({ definition: { openapi: '3.0.3', info: { title: 'CareerHub API', version: '1.0.0' }, servers: [{ url: '/api/v1' }] }, apis: ['./dist/modules/**/*.js'] });
app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use(notFound);
app.use(errorHandler);
