import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, apiEnvelope } from '../api/client';
import { usePageTitle } from '../hooks/usePageTitle';

type Section = 'dashboard'|'users'|'companies'|'jobs'|'applications'|'payments'|'subscriptions'|'audit';
type RecordItem = Record<string, unknown>;
type Stats = { users: number; companies: number; jobs: number; applications: number; pendingCompanies: number; activeSubscriptions: number; totalRevenueEgp: number };
const titles: Record<Section,string> = { dashboard:'Platform overview', users:'Users', companies:'Companies', jobs:'Jobs', applications:'Applications', payments:'Payments', subscriptions:'Subscriptions', audit:'Audit logs' };

export default function AdminPage({ section }: { section: Section }) {
    usePageTitle("Admin");
  const [stats,setStats]=useState<Stats|null>(null);const [rows,setRows]=useState<RecordItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [page,setPage]=useState(1);const [totalPages,setTotalPages]=useState(1);
  const endpoint=section==='users'?'/admin/users':section==='companies'?'/admin/companies':section==='jobs'?'/admin/jobs':section==='applications'?'/admin/applications':section==='payments'?'/billing/admin/payments':section==='subscriptions'?'/admin/subscriptions':section==='audit'?'/admin/audit-logs':'';
  const exportEndpoint=section==='users'?'/admin/users/export':section==='companies'?'/admin/companies/export':section==='jobs'?'/admin/jobs/export':section==='applications'?'/admin/applications/export':'';
  const load=useCallback(async()=>{setLoading(true);setError('');try{if(section==='dashboard')setStats(await api<Stats>('/admin/dashboard'));else if(endpoint){const result=await apiEnvelope<RecordItem[]>(`${endpoint}?page=${page}&limit=25`);setRows(result.data);setTotalPages(result.meta?.totalPages??1);}}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load admin data.');}finally{setLoading(false);}},[endpoint,page,section]);
  useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>rows.filter((row)=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),[rows,query]);
  async function mutate(row:RecordItem){try{
    if(section==='users'){const status=row.status==='BANNED'?'ACTIVE':'BANNED';await api(`/admin/users/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status})});}
    if(section==='companies'){const verificationStatus=row.verificationStatus==='VERIFIED'?'PENDING':'VERIFIED';await api(`/admin/companies/${row.id}/verification`,{method:'PATCH',body:JSON.stringify({verificationStatus})});}
    if(section==='jobs'){const status=row.status==='CLOSED'?'PUBLISHED':'CLOSED';await api(`/admin/jobs/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status})});}
    if(section==='applications'){const status=row.status==='REJECTED'?'REVIEWING':'REJECTED';await api(`/admin/applications/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status})});}
    await load();
  }catch(reason){setError(reason instanceof Error?reason.message:'Could not update this record.');}}
  const count=(value:unknown)=>typeof value==='number'?value.toLocaleString():'—';
  const exportUrl=exportEndpoint?`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000/api/v1'}${exportEndpoint}`:null;
  return <main className="admin-page"><section className="jobs-container"><header className="admin-header"><div><p className="eyebrow">CAREERHUB · OPERATIONS</p><h1>{titles[section]}</h1><p>Platform controls and account oversight.</p></div><nav aria-label="Admin sections">{(['dashboard','users','companies','jobs','applications','payments','subscriptions','audit'] as Section[]).map((key)=><Link key={key} className={key===section?'active':''} to={key==='dashboard'?'/admin':`/admin/${key==='audit'?'audit':key}`}>{titles[key]}</Link>)}</nav></header>
    {error&&<p className="message error" role="alert">{error}</p>}
    {section==='dashboard'&&stats&&<div className="admin-stats"><article className="admin-stat"><p className="eyebrow">USERS</p><strong>{count(stats.users)}</strong><Link to="/admin/users">Manage users →</Link></article><article className="admin-stat"><p className="eyebrow">COMPANIES</p><strong>{count(stats.companies)}</strong><small>{stats.pendingCompanies} pending approval</small><Link to="/admin/companies">Review companies →</Link></article><article className="admin-stat"><p className="eyebrow">JOBS</p><strong>{count(stats.jobs)}</strong><Link to="/admin/jobs">Manage jobs →</Link></article><article className="admin-stat"><p className="eyebrow">APPLICATIONS</p><strong>{count(stats.applications)}</strong><Link to="/admin/applications">Manage applications →</Link></article><article className="admin-stat admin-stat-revenue"><p className="eyebrow">TOTAL REVENUE</p><strong>{count(stats.totalRevenueEgp)} EGP</strong><small>{stats.activeSubscriptions} active paid subscriptions</small></article></div>}
    {section!=='dashboard'&&<><div className="admin-toolbar"><label className="admin-search">Search this page of {section}<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={`Search ${section.toLowerCase()}…`}/></label>{exportUrl&&<a className="secondary-button" href={exportUrl} download>Export CSV ↓</a>}</div>{loading?<div className="jobs-state"><div className="jobs-loader"/><h2>Loading records…</h2></div>:filtered.length===0?<div className="jobs-state"><h2>No matching records</h2><p>Try a different search.</p></div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr>{section==='users'?<><th>User</th><th>Role</th><th>Status</th><th>Created</th></>:section==='companies'?<><th>Company</th><th>Owner</th><th>Open roles</th><th>Verification</th></>:section==='jobs'?<><th>Job</th><th>Company</th><th>Applications</th><th>Status</th></>:section==='payments'?<><th>Company</th><th>Plan</th><th>Amount</th><th>Status</th><th>Date</th></>:section==='subscriptions'?<><th>Company</th><th>Plan</th><th>Status</th><th>Renews</th><th>Last payment</th></>:section==='audit'?<><th>Actor</th><th>Action</th><th>Target</th><th>When</th></>:<><th>Applicant</th><th>Job</th><th>Company</th><th>Status</th></>}{section==='users'||section==='companies'||section==='jobs'||section==='applications'?<th>Action</th>:null}</tr></thead><tbody>{filtered.map((row)=>{const company=row.company as RecordItem|undefined;const user=row.user as RecordItem|undefined;const job=row.job as RecordItem|undefined;const owner=row.owner as RecordItem|undefined;const counts=row._count as RecordItem|undefined;const lastPayment=row.lastPayment as RecordItem|undefined;return <tr key={String(row.id)}>
      {section==='users'&&<><td>{String(row.email)}</td><td>{String(row.role)}</td><td><span className="application-badge">{String(row.status)}</span></td><td>{new Date(String(row.createdAt)).toLocaleDateString()}</td></>}
      {section==='companies'&&<><td><strong>{String(row.name)}</strong><small>{String(row.industry??'')}</small></td><td>{String(owner?.email??'')}</td><td>{count(counts?.jobs)}</td><td><span className="application-badge">{String(row.verificationStatus)}</span></td></>}
      {section==='jobs'&&<><td><strong>{String(row.title)}</strong><small>{String(row.location??'Location flexible')}</small></td><td>{String(company?.name??'')}</td><td>{count(counts?.applications)}</td><td><span className="application-badge">{String(row.status)}</span></td></>}
      {section==='applications'&&<><td>{String(user?.email??'')}</td><td>{String(job?.title??'')}</td><td>{String(company?.name??'')}</td><td><span className="application-badge">{String(row.status)}</span></td></>}
      {section==='payments'&&<><td>{String(row.company??'')}</td><td>{String(row.plan??'')}</td><td>{count(row.amount)} {String(row.currency??'EGP')}</td><td><span className="application-badge">{String(row.status??'')}</span></td><td>{row.createdAt?new Date(String(row.createdAt)).toLocaleDateString():'—'}</td></>}
      {section==='subscriptions'&&<><td>{String(row.company??'')}</td><td>{String(row.plan??'')}</td><td><span className="application-badge">{String(row.status??'')}</span></td><td>{row.currentPeriodEnd?new Date(String(row.currentPeriodEnd)).toLocaleDateString():'—'}</td><td>{lastPayment?`${count(lastPayment.amount)} EGP`: '—'}</td></>}
      {section==='audit'&&<><td>{String(row.actor??'')}</td><td><code className="audit-action">{String(row.action??'')}</code></td><td>{String(row.target??'')}</td><td>{row.createdAt?new Date(String(row.createdAt)).toLocaleString():'—'}</td></>}
      {(section==='users'||section==='companies'||section==='jobs'||section==='applications')&&<td><button className="secondary-button" type="button" onClick={()=>mutate(row)}>{section==='users'?(row.status==='BANNED'?'Enable':'Suspend'):section==='companies'?(row.verificationStatus==='VERIFIED'?'Unverify':'Verify'):section==='jobs'?(row.status==='CLOSED'?'Reopen':'Close'):row.status==='REJECTED'?'Reopen':'Reject'}</button></td>}
    </tr>;})}</tbody></table></div>}{totalPages>1&&<nav className="admin-pagination" aria-label="Admin table pages"><button className="secondary-button" type="button" disabled={page===1||loading} onClick={()=>setPage((current)=>current-1)}>Previous</button><span>Page {page} of {totalPages}</span><button className="secondary-button" type="button" disabled={page>=totalPages||loading} onClick={()=>setPage((current)=>current+1)}>Next</button></nav>}</>}
  </section></main>;
}
