import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { applyToJob, getJob, type Job } from '../api/jobs';
import { api } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { getMyApplications } from '../api/applications';
import { usePageTitle } from '../hooks/usePageTitle';

export default function JobDetails() {
    usePageTitle("Job details");
  const { id = '' } = useParams(); const { user } = useAuth();
  const [job,setJob]=useState<Job|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [applied,setApplied]=useState(false);const [saved,setSaved]=useState(false);const [coverLetter,setCoverLetter]=useState('');const [submitting,setSubmitting]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{let active=true;Promise.all([getJob(id),user?.role==='JOB_SEEKER'?getMyApplications(1,100):Promise.resolve(null),user?.role==='JOB_SEEKER'?api<{saved:boolean}>(`/jobs/${id}/saved`):Promise.resolve(null)]).then(([result,applications,savedState])=>{if(!active)return;setJob(result);setApplied(Boolean(applications?.data.some((application)=>application.jobId===id)));setSaved(Boolean(savedState?.saved));}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'Unable to load this job.')).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[id,user?.role]);
  async function apply(event:FormEvent){event.preventDefault();setSubmitting(true);setError('');setMessage('');try{await applyToJob(id,{coverLetter:coverLetter.trim()||undefined});setApplied(true);setMessage('Application submitted. You can track it from your dashboard.');}catch(reason){setError(reason instanceof Error?reason.message:'Application could not be submitted.');}finally{setSubmitting(false);}}
  async function toggleSave(){if(!user){setError('Sign in as a job seeker to save jobs.');return;}try{await api<void>(`/jobs/${id}/saved`,{method:saved?'DELETE':'POST'});setSaved(!saved);}catch(reason){setError(reason instanceof Error?reason.message:'Could not update saved jobs.');}}
  if(loading)return <main className="jobs-page"><div className="jobs-state"><div className="jobs-loader"/><h2>Loading opportunity…</h2></div></main>;
  if(error&&!job)return <main className="jobs-page"><div className="jobs-state"><p className="eyebrow">OPPORTUNITY UNAVAILABLE</p><h1>We couldn’t find this role.</h1><p>{error}</p><Link to="/jobs" className="applications-button">Back to jobs</Link></div></main>;
  if(!job)return null;
  const salary=job.salaryMin||job.salaryMax?`${job.salaryMin?.toLocaleString()??'—'} – ${job.salaryMax?.toLocaleString()??'—'} ${job.currency}`:'Salary not listed';
  return <main className="jobs-page"><section className="jobs-container"><div className="job-detail-header"><Link to="/jobs" className="back-link">← All opportunities</Link><div className="job-detail-title"><div className="company-mark">{job.company.logoUrl?<img src={job.company.logoUrl} alt={`${job.company.name} logo`}/>:job.company.name.slice(0,1)}</div><div><p className="eyebrow">{job.category}</p><h1>{job.title}</h1><Link to={`/company/${job.company.slug}`}>{job.company.name} ↗</Link></div></div><div className="job-quick-facts"><span>⌖ {job.location??'Flexible location'}</span><span>{job.workplaceType}</span><span>{job.employmentType.replace('_',' ')}</span><span>{job.experienceLevel}</span></div><div className="job-detail-actions">{user?.role==='JOB_SEEKER'?(applied?<span className="application-badge">Application submitted</span>:<form onSubmit={apply} className="apply-form"><label htmlFor="cover-letter">Cover letter <span>(optional)</span></label><textarea id="cover-letter" rows={4} maxLength={5000} value={coverLetter} onChange={(event)=>setCoverLetter(event.target.value)} placeholder="Share what makes you a strong fit."/><button className="primary-button" type="submit" disabled={submitting}>{submitting?'Submitting…':'Apply now'}</button></form>):!user?<Link to="/login" className="primary-button">Sign in to apply</Link>:null}<button type="button" className="secondary-button" onClick={toggleSave}>{saved?'Saved':'Save job'}</button><button type="button" className="secondary-button" onClick={()=>navigator.clipboard?.writeText(window.location.href).then(()=>setMessage('Job link copied.')).catch(()=>setError('Could not copy the link.'))}>Share</button></div>{error&&<p className="message error" role="alert">{error}</p>}{message&&<p className="message success" role="status">{message}</p>}</div>
    <div className="job-detail-layout"><article className="job-description"><section><p className="eyebrow">THE ROLE</p><h2>Job description</h2><p>{job.description}</p></section>{job.requirements&&<section><p className="eyebrow">WHAT YOU’LL NEED</p><h2>Requirements</h2><p>{job.requirements}</p></section>}</article><aside className="job-overview"><p className="eyebrow">ROLE SNAPSHOT</p><h2>At a glance</h2><dl><div><dt>Compensation</dt><dd>{salary}</dd></div><div><dt>Location</dt><dd>{job.location??'Flexible'}</dd></div><div><dt>Workplace</dt><dd>{job.workplaceType}</dd></div><div><dt>Employment</dt><dd>{job.employmentType.replace('_',' ')}</dd></div><div><dt>Experience</dt><dd>{job.experienceLevel}</dd></div><div><dt>Published</dt><dd>{job.publishedAt?new Date(job.publishedAt).toLocaleDateString():'Recently'}</dd></div></dl><Link to={`/company/${job.company.slug}`} className="secondary-button">About {job.company.name}</Link></aside></div>
  </section></main>;
}
