import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { createJob, getMyCompanyJobs, updateJob, type CreateJobInput, type ManagedJob } from '../api/jobs';

const initial: CreateJobInput = { title:'',description:'',requirements:'',category:'',location:'',employmentType:'FULL_TIME',workplaceType:'HYBRID',experienceLevel:'MID',currency:'EGP',status:'DRAFT' };
export default function ManageJob() {
  const { id }=useParams(); const navigate=useNavigate(); const [form,setForm]=useState<CreateJobInput>(initial);const [loading,setLoading]=useState(Boolean(id));const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
  useEffect(()=>{if(!id)return;getMyCompanyJobs().then((items)=>{const job=items.find((item)=>item.id===id) as ManagedJob|undefined;if(!job)throw new Error('Job not found or you do not have access.');setForm({title:job.title,description:job.description,requirements:job.requirements??'',category:job.category,location:job.location??'',employmentType:job.employmentType,workplaceType:job.workplaceType,experienceLevel:job.experienceLevel,salaryMin:job.salaryMin??undefined,salaryMax:job.salaryMax??undefined,currency:job.currency,status:job.status==='ARCHIVED'?'CLOSED':job.status});}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'Could not load job.')).finally(()=>setLoading(false));},[id]);
  function field<K extends keyof CreateJobInput>(key:K,value:CreateJobInput[K]){setForm((current)=>({...current,[key]:value}));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');setSuccess('');try{if(form.description.trim().length<30)throw new Error('Description must be at least 30 characters.');if(form.salaryMin!==undefined&&form.salaryMax!==undefined&&form.salaryMin>form.salaryMax)throw new Error('Minimum salary must not exceed maximum salary.');const payload={...form,title:form.title.trim(),description:form.description.trim(),category:form.category.trim(),requirements:form.requirements?.trim()||undefined,location:form.location?.trim()||undefined};const saved=id?await updateJob(id,payload):await createJob(payload);setSuccess(id?'Your changes are saved.':'Your job has been created.');if(!id)navigate(`/company/jobs/${saved.id}/edit`,{replace:true});}catch(reason){setError(reason instanceof Error?reason.message:'Could not save job.');}finally{setSaving(false);}}
  async function closeJob(){if(!id)return;setSaving(true);try{await updateJob(id,{status:'CLOSED'});setForm((current)=>({...current,status:'CLOSED'}));setSuccess('This job is now closed.');}catch(reason){setError(reason instanceof Error?reason.message:'Could not close job.');}finally{setSaving(false);}}
  if(loading)return <main className="jobs-page"><div className="jobs-state"><div className="jobs-loader"/><h2>Loading job details…</h2></div></main>;
  return <main className="jobs-page"><section className="jobs-container"><header className="applications-top"><div><p className="eyebrow">HIRING WORKSPACE</p><h1>{id?'Edit job':'Create a job'}</h1><p>Give candidates a clear view of the role and what success looks like.</p></div><Link to="/company/dashboard" className="applications-button">Cancel</Link></header>
    {error&&<p className="message error" role="alert">{error}</p>}{success&&<p className="message success" role="status">{success}</p>}
    <form onSubmit={submit} className="job-editor-form"><section className="editor-section"><p className="eyebrow">01 · ROLE</p><h2>Position details</h2><div className="profile-form-grid"><label>Job title<input required minLength={3} maxLength={180} value={form.title} onChange={(event)=>field('title',event.target.value)}/></label><label>Category<input required minLength={2} maxLength={100} value={form.category} onChange={(event)=>field('category',event.target.value)}/></label><label>Location<input value={form.location} onChange={(event)=>field('location',event.target.value)} placeholder="Cairo, Egypt"/></label><label>Employment type<select value={form.employmentType} onChange={(event)=>field('employmentType',event.target.value as CreateJobInput['employmentType'])}>{['FULL_TIME','PART_TIME','CONTRACT','INTERNSHIP','FREELANCE'].map((value)=><option key={value}>{value}</option>)}</select></label><label>Workplace<select value={form.workplaceType} onChange={(event)=>field('workplaceType',event.target.value as CreateJobInput['workplaceType'])}>{['ONSITE','HYBRID','REMOTE'].map((value)=><option key={value}>{value}</option>)}</select></label><label>Experience level<select value={form.experienceLevel} onChange={(event)=>field('experienceLevel',event.target.value as CreateJobInput['experienceLevel'])}>{['ENTRY','JUNIOR','MID','SENIOR','LEAD','EXECUTIVE'].map((value)=><option key={value}>{value}</option>)}</select></label></div></section>
      <section className="editor-section"><p className="eyebrow">02 · OVERVIEW</p><h2>Describe the opportunity</h2><label>Description<textarea required minLength={30} maxLength={10000} rows={8} value={form.description} onChange={(event)=>field('description',event.target.value)}/></label><label>Requirements<textarea maxLength={10000} rows={6} value={form.requirements} onChange={(event)=>field('requirements',event.target.value)} placeholder="Experience, skills, and qualifications"/></label></section>
      <section className="editor-section"><p className="eyebrow">03 · COMPENSATION & STATUS</p><h2>Set expectations</h2><div className="profile-form-grid"><label>Minimum salary<input type="number" min="0" value={form.salaryMin??''} onChange={(event)=>field('salaryMin',event.target.value===''?undefined:Number(event.target.value))}/></label><label>Maximum salary<input type="number" min="0" value={form.salaryMax??''} onChange={(event)=>field('salaryMax',event.target.value===''?undefined:Number(event.target.value))}/></label><label>Currency<input required maxLength={3} minLength={3} value={form.currency} onChange={(event)=>field('currency',event.target.value.toUpperCase())}/></label><label>Publication status<select value={form.status} onChange={(event)=>field('status',event.target.value as CreateJobInput['status'])}><option value="DRAFT">Save as draft</option><option value="PUBLISHED">Publish job</option>{id&&<option value="CLOSED">Close job</option>}</select></label></div></section>
      <footer className="editor-actions"><button className="primary-button" type="submit" disabled={saving}>{saving?'Saving…':id?'Save changes':form.status==='PUBLISHED'?'Publish job':'Save draft'}</button>{id&&form.status!=='CLOSED'&&<button className="danger-button" type="button" disabled={saving} onClick={closeJob}>Close this job</button>}<Link to="/company/dashboard" className="secondary-button">Cancel</Link></footer>
    </form>
  </section></main>;
}
